export type Locale = "es";

interface Dictionary {
  [key: string]: string | Dictionary;
}

const es: Dictionary = {
  app: { name: "FulbITo" },
  common: {
    loading: "Cargando…",
    create: "Crear",
    close: "Cerrar",
    delete: "Eliminar",
    add: "Agregar",
    save: "Guardar",
    search: "Buscar",
  },
  login: {
    heroTitle: "Código, deploy y gol.",
    heroCopy:
      "Organizá partidos con tu equipo de IT, calificá el desempeño y seguí la evolución de cada jugador.",
    title: "Ingresar",
    subtitle: "Entrá para gestionar tus partidos y jugadores.",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Contraseña",
    forgot: "¿Olvidaste tu contraseña?",
    action: "Entrar",
    actionLoading: "Ingresando…",
    noAccount: "¿No tenés cuenta?",
    registerCta: "Registrate",
  },
  register: {
    heroTitle: "Sumate al equipo.",
    heroCopy:
      "Creá tu cuenta, reclamá tu jugador y empezá a sumar minutos y rating en cada partido.",
    title: "Crear cuenta",
    subtitle: "Configura tu acceso para participar de los partidos.",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Contraseña",
    autoRedirect: "Redirigir automáticamente",
    action: "Registrarme",
    actionLoading: "Creando…",
    haveAccount: "¿Ya tenés cuenta?",
    loginCta: "Ingresá",
    duplicateEmail: "Ya existe un usuario registrado con ese email",
    missingToken: "Registro sin token en la respuesta",
    error: "Error de registro",
  },
  groups: {
    loading: "Cargando grupos…",
    createTitle: "Crear grupo",
    namePlaceholder: "Nombre del grupo",
    descPlaceholder: "Descripción (opcional)",
    creating: "Creando…",
    create: "Crear grupo",
    owner: "Owner",
    member: "Miembro",
    playersSuffix: "jugadores",
    addPlayers: "Agregar jugadores",
    addPlayersTitle: "Solo el owner puede agregar jugadores",
    delete: "Eliminar",
    deleteTitle: "Eliminar grupo",
    searchPlayer: "Buscar jugador…",
    selectAll: "Seleccionar todo",
    addCount: "Agregar",
    close: "Cerrar",
    deleteError: "No se pudo eliminar el grupo",
  },
  matches: {
    loading: "Cargando partidos…",
    chooseGroup: "Elegí un grupo",
    create: "Crear partido",
    noPermissionCreate: "No tenés permiso para crear partidos en este grupo",
    groupNoPlayers: "Este grupo no tiene jugadores todavía.",
    selectGroupSeePlayers: "Elegí un grupo para ver sus jugadores.",
    open: "Abrir",
    delete: "Eliminar",
    noDate: "Sin fecha",
    deleteError: "No se pudo eliminar el partido",
    matchesTitle: "Partidos",
  },
  matchDetail: {
    loading: "Cargando partido…",
    title: "Partido",
    generating: "Generando…",
    generateTeams: "Generar equipos",
    noPermission: "Sin permiso",
    teamA: "Equipo A (claro)",
    teamB: "Equipo B (oscuro)",
    signedPlayers: "Jugadores anotados",
    noSignedPlayers: "Este partido no tiene jugadores anotados todavía.",
    result: "Resultado",
    finalizedAt: "Finalizado:",
    finalize: "Finalizar",
    needTeamsFirst: "Primero generá los equipos para poder finalizar.",
    ratePlayers: "Calificar jugadores",
    allRated: "Todos calificados. Ahora podés aplicar los ratings.",
    bad: "Mal desempeño",
    neutral: "Neutral",
    good: "Buen desempeño",
    applying: "Aplicando…",
    apply: "Aplicar ratings",
    waitingOrganizer: "Esperando que el organizador aplique los ratings…",
    pendingYourVotes:
      "Votá a los jugadores restantes para cerrar tu parte de la votación.",
    ratingChanges: "Cambios de rating",
    noChanges: "Sin cambios registrados.",
    colPlayer: "Jugador",
    colBefore: "Antes",
    colAfter: "Después",
    colDelta: "Δ",
    confirmApply:
      "¿Aplicar ratings ahora? Esto cerrará la votación para todos.",
    applyError: "No se pudieron aplicar los ratings",
    voteError: "No se pudo enviar el voto",
    editResult: "Editar resultado",
    updateResult: "Actualizar resultado",
    cancel: "Cancelar",
    cannotEditApplied: "No se puede editar después de aplicar ratings",
    updateResultError: "No se pudo actualizar el resultado",
  },
  players: {
    loading: "Cargando jugadores…",
    title: "Jugadores",
    createTitle: "Crear jugador",
    name: "Nombre",
    nickname: "Apodo (opcional)",
    create: "Crear",
    new: "Nuevo",
    myProfile: "Mi perfil",
    unclaim: "Desvincular",
    claimed: "Asignado",
    claim: "Vincularme",
    deleteTitle: "Eliminar jugador",
    gamesPlayed: "Partidos jugados:",
    zeroHint: "0 = no informar",
    claimError: "No se pudo reclamar el jugador",
    unclaimError: "No se pudo desvincular el jugador",
    deleteError: "No se pudo eliminar el jugador",
  },
  playerDetail: {
    loading: "Cargando jugador…",
    back: "← Volver",
    title: "Perfil del Jugador",
    myProfile: "Mi perfil",
    claimed: "Asignado",
    gamesPlayed: "Partidos jugados:",
    rating: "Rating:",
    createdAt: "Creado:",
    updatedAt: "Actualizado:",
    skills: "Skills",
    onlyOwner: "Solo el dueño puede editar",
    zeroHint: "0 = no informar",
    saving: "Guardando…",
    save: "Guardar cambios",
    saveError: "No se pudo guardar",
    loadError: "No se pudo cargar el jugador",
    refreshFallback: "No se pudo refrescar desde el backend",
    showingLocal: "(Mostrando datos locales)",
    statsTitle: "Rendimiento",
    wins: "Ganados",
    losses: "Perdidos",
    draws: "Empatados",
    total: "Total",
    record: "Registro",
    winRate: "% Victorias",
    noStatsYet: "Sin partidos finalizados todavía",
    statsError: "No se pudieron calcular las estadísticas",
  },
  forgot: {
    step1: "Recuperar contraseña",
    step2: "Ingresá el código",
    step3: "Nueva contraseña",
    email: "Email",
    sending: "Enviando…",
    sendCode: "Enviar código",
    devCode: "Dev code:",
    instruction: "Ingresa el código para generar una nueva contraseña",
    code: "Código",
    verifying: "Verificando…",
    verify: "Verificar",
    newPassword: "Nueva contraseña",
    saving: "Guardando…",
    saveNew: "Guardar nueva contraseña",
    errorSend: "Error enviando código",
    errorCode: "Código inválido",
    errorReset: "No se pudo resetear",
    backLogin: "Volver al login",
  },
  nav: {
    matches: "Partidos",
    groups: "Grupos",
    players: "Jugadores",
    logout: "Salir",
    login: "Login",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
  },
};

let current: Locale = "es";
const dictionaries: Record<Locale, Dictionary> = { es };

function resolve(path: string, dict: Dictionary): string {
  const parts = path.split(".");
  let node: any = dict;
  for (const p of parts) {
    if (node && typeof node === "object" && p in node) node = node[p];
    else return path; // fallback to key
  }
  return typeof node === "string" ? node : path;
}

export function t(key: string): string {
  return resolve(key, dictionaries[current]);
}
export function setLocale(loc: Locale) {
  if (loc in dictionaries) current = loc;
}
